# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 火山极速版199

on:
  workflow_dispatch:
#  schedule:
#     - cron: '*/2 * * * *'
#  watch:
#    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        HOTSOONSIGNHEADER: ${{ secrets.HOTSOONSIGNHEADER }}
        HOTSOONSIGNKEY: ${{ secrets.HOTSOONSIGNKEY }}
        HOTSOONADHEADER: ${{ secrets.HOTSOONADHEADER }}
        HOTSOONADKEY: ${{ secrets.HOTSOONADKEY }}        
        HOTSOONREADHEADER: ${{ secrets.HOTSOONREADHEADER }}
        HOTSOONREADKEY: ${{ secrets.HOTSOONREADKEY }} 
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/gz154838009/script-1.git ~/script-1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/script-1
          npm install
      - name: '运行 【火山极速版】'
        run: |
          cd ~/script-1
          node hotsoon_old.js
        env:  
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}



    
